# Generated by Django 5.2.4 on 2025-08-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_education_experience_personalinfo_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for course cards', max_length=200)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=50)),
                ('duration_hours', models.IntegerField(help_text='Estimated course duration in hours')),
                ('price', models.DecimalField(decimal_places=2, help_text='Course price (0 for free)', max_digits=10)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='course_images')),
                ('prerequisites', models.TextField(blank=True, help_text='What students should know before taking this course')),
                ('what_you_learn', models.TextField(help_text='What students will learn from this course')),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies covered', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or other video URL', null=True)),
                ('duration_minutes', models.IntegerField(help_text='Lesson duration in minutes')),
                ('order', models.IntegerField(default=0)),
                ('is_free_preview', models.BooleanField(default=False, help_text='Allow free preview of this lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='portfolioapp.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
    ]
