# Generated by Django 5.2.4 on 2025-08-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_course_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
